// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diomduaztdihypkcobmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpb21kdWF6dGRpaHlwa2NvYm14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1MzU5MTQsImV4cCI6MjA4ODExMTkxNH0.EPA73a7_7abXxocap8buZt5Wyr6quzB0eKz-WzF5Es4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});